"""Rename email_id to thread_id

Revision ID: 5f399cb3700f
Revises: e7c5e38a3281
Create Date: 2026-01-14 16:30:00.141627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f399cb3700f'
down_revision: Union[str, None] = 'e7c5e38a3281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('thread_id', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_emails_email_id'), table_name='emails')
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=True)
    op.drop_column('emails', 'email_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('email_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.create_index(op.f('ix_emails_email_id'), 'emails', ['email_id'], unique=True)
    op.drop_column('emails', 'thread_id')
    # ### end Alembic commands ###

